site_name: "Virtualization Proxmox 8.4.1 docs"
repo_url: "https://github.com/ifezgez/virtualization"
theme:
  name: material
markdown_extensions: [admonition, codehilite, toc]
nav:
  - Home: docs/index.md
  - Proxmox 8.4.1:
      - Installation: docs/proxmox/8.4.1/bare-metal/docs/installation.md
      - Networking:   docs/proxmox/8.4.1/bare-metal/docs/network.md
      - Cluster:      docs/proxmox/8.4.1/bare-metal/docs/cluster.md
      - Ceph:         docs/proxmox/8.4.1/bare-metal/docs/ceph.md
      - HA:           docs/proxmox/8.4.1/bare-metal/docs/ha.md
