site_name: "Proxmox VE 8.4.1 docs"
repo_url:  "https://github.com/vestasec/virtualization"
docs_dir: .
theme:
  name: material
markdown_extensions:
  - admonition
  - codehilite
  - toc
nav:
  - Installation: proxmox/8.4.1/bare-metal/docs/installation.md
  - Networking:   proxmox/8.4.1/bare-metal/docs/network.md
  - Cluster:      proxmox/8.4.1/bare-metal/docs/cluster.md
  - Ceph Storage: proxmox/8.4.1/bare-metal/docs/ceph.md
  - High Availability: proxmox/8.4.1/bare-metal/docs/ha.md
  - Troubleshooting:
      - Cluster: proxmox/8.4.1/bare-metal/docs/troubleshooting_cluster.md
      - Ceph:    proxmox/8.4.1/bare-metal/docs/troubleshooting_ceph.md
